#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUTPUT_DIR="$ROOT_DIR/src-tauri/tests/fixtures/compat"
WORK_DIR="$(mktemp -d)"
SOURCE_DIR="$WORK_DIR/compat-source"
RAW_DIR="$SOURCE_DIR/raw"

cleanup() {
  rm -rf "$WORK_DIR"
}
trap cleanup EXIT

mkdir -p "$OUTPUT_DIR"
rm -f \
  "$OUTPUT_DIR"/*.zip \
  "$OUTPUT_DIR"/*.tar \
  "$OUTPUT_DIR"/*.gz \
  "$OUTPUT_DIR"/*.bz2 \
  "$OUTPUT_DIR"/*.xz \
  "$OUTPUT_DIR"/*.7z

mkdir -p \
  "$SOURCE_DIR/docs/nested" \
  "$SOURCE_DIR/unicode/thử-nghiệm" \
  "$SOURCE_DIR/empty-dir" \
  "$RAW_DIR"

cat > "$SOURCE_DIR/docs/readme.txt" <<'EOF'
Ziply compatibility fixture
EOF

cat > "$SOURCE_DIR/docs/nested/config.json" <<'EOF'
{"name":"ziply","mode":"compat-fixture"}
EOF

cat > "$SOURCE_DIR/unicode/thử-nghiệm/điện-toán.txt" <<'EOF'
Nội dung unicode cho compatibility fixture.
EOF

: > "$SOURCE_DIR/docs/blank.txt"

python3 - <<'PY' "$RAW_DIR/stream.bin"
from pathlib import Path
import sys

path = Path(sys.argv[1])
payload = bytes(((index * 29 + 7) % 251) for index in range(65536 + 19))
path.write_bytes(payload)
PY

(
  cd "$WORK_DIR"
  /usr/bin/zip -rq "$OUTPUT_DIR/zip-cli.zip" "compat-source"
  /usr/bin/zip -rq -P "ziply-secret" "$OUTPUT_DIR/zip-cli-encrypted.zip" "compat-source"
  /usr/bin/ditto -c -k --keepParent "compat-source" "$OUTPUT_DIR/zip-ditto.zip"
  /usr/bin/tar -cf "$OUTPUT_DIR/tar-cli.tar" "compat-source"
  /usr/bin/tar -czf "$OUTPUT_DIR/tar-cli.tar.gz" "compat-source"
  /usr/bin/bsdtar -caf "$OUTPUT_DIR/tar-bsdtar.tar.bz2" "compat-source"
  /usr/bin/bsdtar -caf "$OUTPUT_DIR/tar-bsdtar.tar.xz" "compat-source"
  /opt/homebrew/bin/7zz a -t7z -mx=5 "$OUTPUT_DIR/7zz-cli.7z" "compat-source" >/dev/null
  /opt/homebrew/bin/7zz a -t7z -mx=5 -p"ziply-secret" -mhe=on "$OUTPUT_DIR/7zz-cli-encrypted.7z" "compat-source" >/dev/null
)

/usr/bin/gzip -c "$RAW_DIR/stream.bin" > "$OUTPUT_DIR/raw-gzip.gz"
/usr/bin/bzip2 -c "$RAW_DIR/stream.bin" > "$OUTPUT_DIR/raw-bzip2.bz2"
/opt/homebrew/bin/xz -c "$RAW_DIR/stream.bin" > "$OUTPUT_DIR/raw-xz.xz"

cat > "$OUTPUT_DIR/README.md" <<'EOF'
# Compatibility Fixtures

These archives are generated by `scripts/generate-compat-fixtures.sh`.

Current sources:

- `/usr/bin/zip`
- `/usr/bin/ditto`
- `/usr/bin/tar`
- `/usr/bin/bsdtar`
- `/usr/bin/gzip`
- `/usr/bin/bzip2`
- `/opt/homebrew/bin/xz`
- `/opt/homebrew/bin/7zz`

The encrypted ZIP fixture uses password `ziply-secret`.
The encrypted 7Z fixture also uses password `ziply-secret`.
EOF
